//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log_in
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRANCH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BRANCH()
        {
            this.ACCOUNTs = new HashSet<ACCOUNT>();
            this.EMPLOYEEs = new HashSet<EMPLOYEE>();
            this.LOANs = new HashSet<LOAN>();
        }
    
        public long BRANCH_ID { get; set; }
        public long CODE { get; set; }
        public string USERNAMEADMIN { get; set; }
        public string NAME_BRANCH { get; set; }
        public string STREET_BRANCH { get; set; }
        public string CITY_BRANCH { get; set; }
        public string COUNTRY_BRANCH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCOUNT> ACCOUNTs { get; set; }
        public virtual ADMIN ADMIN { get; set; }
        public virtual BANK BANK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE> EMPLOYEEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOAN> LOANs { get; set; }
    }
}
