//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log_in
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUTOMER_PHONE
    {
        public long PHONE { get; set; }
        public long SSN_CUSTOMER { get; set; }
        public long SSN { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
