//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log_in
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.EMPLOYEE_PHONE = new HashSet<EMPLOYEE_PHONE>();
            this.LOANs = new HashSet<LOAN>();
        }
    
        public long EMPLOYEE_ID { get; set; }
        public Nullable<long> BRANCH_ID { get; set; }
        public string STREET_EMPLOYEE { get; set; }
        public string CITY_EMPLOYEE { get; set; }
        public string COUNTRY_EMPLOYEE { get; set; }
        public string FNAME_EMPLOYEE { get; set; }
        public string LNAME_EMPLOYEE { get; set; }
        public string USERNAME_ADMIN { get; set; }
        public string PASSWORD_ADMIN { get; set; }
    
        public virtual BRANCH BRANCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE_PHONE> EMPLOYEE_PHONE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOAN> LOANs { get; set; }
    }
}
