//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log_in
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAN()
        {
            this.EMPLOYEEs = new HashSet<EMPLOYEE>();
            this.CUSTOMERs = new HashSet<CUSTOMER>();
        }
    
        public long LOANNUMBER { get; set; }
        public Nullable<long> LOANAMOUNT { get; set; }
        public string LOANTYPE { get; set; }
        public long BRANCH_ID { get; set; }
        public string STATUS { get; set; }
    
        public virtual BRANCH BRANCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE> EMPLOYEEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER> CUSTOMERs { get; set; }
    }
}
